/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package day7;

/**
 *
 * @author Iqra
 */
public class Day7 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        char inisial = 'I';
        boolean kelasb = true;
        System.out.println("Inisial Nama: "+inisial);
        System.out.println("Kelas B:"+kelasb);
    }
    
}
