package days018;

import java.util.Scanner;

public class Days018 {

    public static void main(String[] args) {
      
        Scanner input = new Scanner(System.in);
        System.out.print("Masukkan Angka:");
        int nilaiInt = input.nextInt();
        double nilaiDouble = nilaiInt;
        
        System.out.println("Nilai Int\t:"+nilaiInt);
        System.out.println("Nilai Double\t:"+nilaiDouble);

    }
}
