/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package days9;

/**
 *
 * @author Iqra
 */
public class Days9 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
       
       
    
        String nama;
        nama = "Iqra";
        System.out.println(nama);
        nama = "iqraa";
        System.out.println(nama);
        
        int tes;
        tes = 1;
        System.out.println(tes);
        tes = 2;
        System.out.println(tes);
    }
    
}
