/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */

package com.mycompany.days4;

/**
 *
 * @author Iqra
 */
public class Days4 {

    public static void main(String[] args) {
        System.out.println("Nama\t:Iqra");
        System.out.println("NIM\t:D00250155");
        System.out.print("Kelas\t:Informatika B\n");
               System.out.print("Days 4 of 100 Days coding 2025\n");
               System.out.println("\"\" Untuk menampilkan Petik dua");
               System.out.println("Contoh:");
               
               System.out.println("Nama Saya \"Iqra\"");
               System.out.println("\\\' Untuk menampilkan petik tunggal");
              System.out.println("Contoh:"); 
              System.out.println("\'Bacalah\' Dalam bahasa indonesia");
               
               System.out.println("\\\\ Untuk menampilkan Backslesh");
    }
}
