* Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */

package com.mycompany.days5;

/**
 *
 * @author Iqra
 */
public class Days5 {

    public static void main(String[] args) {
    
     int kelasb = 28;
     byte gabungankelas = 60;
     short informatika = 400;
     long maba2025 = 3270;
        System.out.println("Jumlah Kelas B \t\t\t:"+kelasb);
        System.out.println("Jumlah Gabungan Kelas A dan B \t:" +gabungankelas);
        System.out.println("Jumlah Maba teknik \t\t:" +informatika);
        System.out.println("Jumlah Maba Unsulbar \t\t:"+maba2025);
    }
