/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Main.java to edit this template
 */
package days10;

/**
 *
 * @author Iqra
 */
public class Days10 {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
      final int A;
      A = 100;
              System.out.println(A);
    }
    
}
