/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 */

package com.mycompany.days2;

/**
 *
 * @author Iqra
 */
public class Days2 {

    public static void main(String[] args) {
  
      
        System.out.print("Days ");
        System.out.print("2 ");
        System.out.println("Of 100 Days Coding 2025");
        System.out.println("Selasa, 09 September 2025");
        System.out.println("Penggunaan:");
        System.out.println("1. Print");
        System.out.println("2. Println");
        System.out.println("3. Printf");
     
      
      System.out.printf("Nama: %s, Umur: %d, NIM: %s",  "Iqra", 18, "D0225015");   
    }
}
